spring:
  sql:
    init:
      mode: never
  docker:
    compose:
      profiles:
        active: pg_14
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        timeout: 10s
        command: stop
      readiness:
        timeout: 2m
        tcp:
          connect-timeout: 200ms
          read-timeout: 200ms
        wait: always